# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centronegocios',
            name='planta',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='centroNegocios',
        ),
        migrations.DeleteModel(
            name='CentroNegocios',
        ),
        migrations.DeleteModel(
            name='Planta',
        ),
        migrations.DeleteModel(
            name='Trabajador',
        ),
    ]
