# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 18:07
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('tipo', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('zona', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='est.Planta')),
                ('riesgo', models.ManyToManyField(to='est.Riesgo')),
            ],
        ),
        migrations.AddField(
            model_name='trabajador',
            name='rut',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='rol',
            name='zonas_permitidas',
            field=models.ManyToManyField(to='est.Zona'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='rol',
            field=models.ManyToManyField(to='est.Rol'),
        ),
    ]
