# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='nivel_riesgo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zona',
            name='nivel_riesgo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
