# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0002_auto_20160216_1446'),
        ('est', '0002_auto_20160216_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='gps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gps.Devices'),
        ),
    ]
