# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0004_auto_20160218_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('fono', models.CharField(max_length=128)),
                ('tipo_contacto', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('rut', models.CharField(blank=True, max_length=128, null=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='est.Contacto')),
            ],
        ),
        migrations.AlterField(
            model_name='planta',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='est.Empresa'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='est.Contacto'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='est.Empresa'),
        ),
    ]
