# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0004_auto_20160301_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='cargo',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='tipo_contacto',
            field=models.CharField(blank=True, choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('ESPOSO', 'Esposa(o)'), ('ABUELO', 'Abuelo(a)'), ('HIJO', 'Hijo(a)'), ('PAREJA', 'Pareja'), ('POLOLO', 'Pololo(a)')], max_length=128, null=True),
        ),
    ]
