# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0005_auto_20160405_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='qrimg',
            field=models.ImageField(blank=True, null=True, upload_to='est/cv/img/qr/'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='qrtext',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='est/cv/img/avatar/'),
        ),
    ]
