# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0005_auto_20160218_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='uso',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
