# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0006_auto_20160505_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='estid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='qrimg',
            field=models.ImageField(blank=True, null=True, upload_to='qr/'),
        ),
    ]
