# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0006_zona_uso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='planta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='est.Planta'),
        ),
        migrations.AlterField(
            model_name='zona',
            name='riesgo',
            field=models.ManyToManyField(blank=True, null=True, to='est.Riesgo'),
        ),
    ]
