# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0007_auto_20160516_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
