# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0008_trabajador_edad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajador',
            old_name='nombre',
            new_name='primer_nombre',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
