# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-15 20:58
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '__first__'),
        ('est', '0009_auto_20160516_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alertatrabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(db_column=b'punto', srid=4326)),
                ('i', models.IntegerField(blank=True, null=True)),
                ('zona', models.CharField(blank=True, max_length=128, null=True)),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('foto', models.CharField(blank=True, max_length=128, null=True)),
                ('fono', models.IntegerField(blank=True, null=True)),
                ('nombre_emergencia', models.CharField(blank=True, max_length=128, null=True)),
                ('nro_emergencia', models.CharField(blank=True, max_length=128, null=True)),
                ('tipo_contacto', models.CharField(blank=True, choices=[(b'PADRE', b'Padre'), (b'MADRE', b'Madre'), (b'ESPOSO', b'Esposa(o)'), (b'ABUELO', b'Abuelo(a)'), (b'HIJO', b'Hijo(a)'), (b'PAREJA', b'Pareja'), (b'POLOLO', b'Pololo(a)')], max_length=128, null=True)),
                ('cargo', models.CharField(blank=True, max_length=128, null=True)),
                ('nivel_riesgo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listacn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Listaplantas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Listatrabajadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Posicionestrabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.IntegerField(blank=True, null=True)),
                ('fixtime', models.DateTimeField(db_column=b'fixTime')),
                ('valid', models.BooleanField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('attributes', models.CharField(max_length=4096)),
                ('geom', django.contrib.gis.db.models.fields.PointField(db_column=b'punto', srid=4326)),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('apellidop', models.CharField(blank=True, max_length=128, null=True)),
                ('apellidom', models.CharField(blank=True, max_length=128, null=True)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=256, null=True)),
                ('fono', models.IntegerField(blank=True, null=True)),
                ('e_mail', models.CharField(blank=True, max_length=128, null=True)),
                ('emergencia', models.IntegerField(blank=True, null=True)),
                ('tipo_contacto', models.CharField(blank=True, choices=[(b'PADRE', b'Padre'), (b'MADRE', b'Madre'), (b'ESPOSO', b'Esposa(o)'), (b'ABUELO', b'Abuelo(a)'), (b'HIJO', b'Hijo(a)'), (b'PAREJA', b'Pareja'), (b'POLOLO', b'Pololo(a)')], max_length=128, null=True)),
                ('rut', models.CharField(blank=True, max_length=128, null=True)),
                ('centroNegocios', models.IntegerField(blank=True, null=True)),
                ('cargo', models.CharField(blank=True, max_length=128, null=True)),
                ('rol', models.IntegerField(blank=True, null=True)),
                ('gps', models.IntegerField(blank=True, null=True)),
                ('supervisor', models.IntegerField(blank=True, null=True)),
                ('empresa', models.IntegerField(blank=True, null=True)),
                ('salud', models.IntegerField(blank=True, null=True)),
                ('estudios', models.IntegerField(blank=True, null=True)),
                ('capacitacion', models.IntegerField(blank=True, null=True)),
                ('nivel_riesgo', models.IntegerField(blank=True, null=True)),
                ('nota', models.CharField(blank=True, max_length=256, null=True)),
                ('nota2', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='testzona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(blank=True, max_length=128, null=True)),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tiempozona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajadorCapacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('observacion', models.CharField(blank=True, max_length=4096, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrabajadorDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gps.Devices')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajadorEstudios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('observacion', models.CharField(blank=True, max_length=4096, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='capacitacion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='capacitacion',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='estudios',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='estudios',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='capacitacion',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='estudios',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='fono_gps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='salud',
            name='detalle',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='gps',
        ),
        migrations.AddField(
            model_name='trabajadordevice',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='est.Trabajador'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='gps',
            field=models.ManyToManyField(blank=True, null=True, through='est.TrabajadorDevice', to='gps.Devices'),
        ),
    ]
