# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-16 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0010_auto_20160615_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='capacitacion',
            field=models.ManyToManyField(blank=True, null=True, through='est.TrabajadorCapacitacion', to='est.Capacitacion'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='estudios',
            field=models.ManyToManyField(blank=True, null=True, through='est.TrabajadorEstudios', to='est.Estudios'),
        ),
        migrations.AddField(
            model_name='trabajadorcapacitacion',
            name='capacitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='est.Capacitacion'),
        ),
        migrations.AddField(
            model_name='trabajadorcapacitacion',
            name='certificado',
            field=models.ImageField(blank=True, null=True, upload_to='capacitacion/'),
        ),
        migrations.AddField(
            model_name='trabajadorcapacitacion',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='est.Trabajador'),
        ),
        migrations.AddField(
            model_name='trabajadorestudios',
            name='certificado',
            field=models.ImageField(blank=True, null=True, upload_to='estudios/'),
        ),
        migrations.AddField(
            model_name='trabajadorestudios',
            name='estudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='est.Estudios'),
        ),
        migrations.AddField(
            model_name='trabajadorestudios',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='est.Trabajador'),
        ),
    ]
