# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-21 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0011_auto_20160616_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajador',
            name='fono_gps',
        ),
        migrations.AddField(
            model_name='trabajadordevice',
            name='fono_gps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
